name: Google Cloud Build and Deploy

on:
  push:
    tags:
      - '*'
      
permissions:
  contents: write
      
jobs:
  publish:
    name: Build Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Extract Tag
        id: vars
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - run: |
          docker compose -f ci/docker-compose.yml build
          docker compose -f ci/docker-compose.yml push

  retag:
    name: Publish to Cloud Run
    needs: publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Extract Tag
        run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Configure gcloud for Artifact Registry
        run: |
          gcloud auth configure-docker ${{ vars.GCP_REGION }}-docker.pkg.dev
      - name: Pull a retag to Google Artifact Registry
        run: |
          docker pull ${{ vars.DOCKERHUB_USERNAME }}/woki-challenge:${TAG_NAME}
          docker tag ${{ vars.DOCKERHUB_USERNAME }}/woki-challenge:${TAG_NAME} \
            ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REPOSITORY }}/woki-challenge:${TAG_NAME}
          docker push ${{ vars.GCP_REGION }}-docker.pkg.dev/${{ vars.GCP_PROJECT }}/${{ vars.GCP_REPOSITORY }}/woki-challenge:${TAG_NAME}
          
  deploy:
    name: Deploy to Cloud Run
    needs: retag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Export variables
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          echo "GCP_REGION=${{ vars.GCP_REGION }}" >> $GITHUB_ENV
          echo "GCP_PROJECT=${{ vars.GCP_PROJECT }}" >> $GITHUB_ENV
          echo "GCP_REPOSITORY=${{ vars.GCP_REPOSITORY }}" >> $GITHUB_ENV
          echo "GCP_SQLITE_BUCKET=${{ vars.GCP_SQLITE_BUCKET }}" >> $GITHUB_ENV
          
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}
      - name: Deploy to Cloud Run
        run: |
          envsubst < ./ci/service.template.yaml > service.yaml
          gcloud run services replace service.yaml \
            --platform=managed \
            --region=${{ vars.GCP_REGION }}

  release:
    name: Create GitHub Release
    needs: publish
    runs-on: ubuntu-slim

    steps:
      - uses: actions/checkout@v5
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body: "Automated release for tag ${{ github.ref_name }}"
          draft: false
          prerelease: false
